tunnel: 256b0144-5cb0-404f-a7fe-57454333634a
credentials-file: ~/.cloudflared/256b0144-5cb0-404f-a7fe-57454333634a.json

ingress:
  - hostname: mangeurdecaca.store
    service: http://localhost:5002
  - service: http_status:404

# Configuration optionnelle
originRequest:
  connectTimeout: 30s
  noHappyEyeballs: false
  keepAliveConnections: 10
  keepAliveTimeout: 90s

# Logs
loglevel: info